version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/backend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/common"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages-frontend"
    schedule:
      interval: "weekly"
